[solution]
name = "sa_indexer"
definition = "dsa_topk_indexer_fp8_h64_d128_topk2048_ps64"
author = "kplc"

[build]
language = "cuda"
entry_point = "dsa_topk_indexer_fp8_h64_d128_topk2048_ps64.cu::dsa_topk_indexer_fp8_h64_d128_topk2048_ps64"
